server:
  port: 8003
#mybatis配置
mybatis:
  type-aliases-package: com.curtain.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#Spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.73.234:3306/DB03?userUnicode=true&characterEncoding=utf-8
    username: root
    password: Wqt19971130@

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8003 #修改eureka上的默认描述信息

#info配置
info:
 app.name: curtain-springcloud
 company.name: zk

