server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名字
  client:
    register-with-eureka: false #表示不向Eureka注册中心注册自己
    fetch-registry: false #表示自己为注册中心,ture的话就是客户端
    service-url:  #监控页面~
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
